### ISSUE TITLE
我请问你有关输入的问题

### ISSUE THREAD

**Issue by andongBlue** [TobiasLee/Chinese_Hip-pop_Generation#11]
你好，我下载了你的数据以及代码，我请问你有关输入的问题。
输入data文件都是id，这些id是什么呢？如何产生的呢？
关于negative_file和word2id__file文件是如何生成的呢？
为什么id数据可进入GAN网络，而不是vec数据呢？
我的问题有点多，有点傻哈，但是困扰我蛮久了，还得请你回答一下，十分感谢！~

**Comment by TobiasLee** [comment]
Hi, 
- id 是 word 经过 tokenization 对应的  word index
- 我们根据词频有小到大对词进行编编码，word2id 就是存储了这个映射关系
- id 经过 embedding 之后变成 vec 进入 GAN
- negative_file 是 generator 在对抗训练过程之中生成的负例样本，用于训练 Discriminator
