### ISSUE TITLE
请问一你的CTEG那篇论文用的什么机器啊，感觉好慢啊

### ISSUE THREAD

**Issue by nlpofwhat** [TobiasLee/Chinese_Hip-pop_Generation#13]

**Comment by TobiasLee** [comment]
1080Ti ，确实比较慢，需要一些耐心。

**Comment by nlpofwhat** [comment]
跑一个epoch需要两天(:)batchsize 只能是32，64就oom了------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 晚上10:33
收件人: "TobiasLee/Chinese-Hip-pop-Generation"<Chinese-Hip-pop-Generation@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TobiasLee/Chinese-Hip-pop-Generation] 请问一你的CTEG那篇论文用的什么机器啊，感觉好慢啊 (#13)



1080Ti ，确实比较慢，需要一些耐心。
 
&mdash;

**Comment by nlpofwhat** [comment]
你好！请问下你那个代码在训练的时候bleu和重新加载模型测试的bleu为什么不一样啊，同一个epoch很奇怪第一次碰到这种情况，有可能是什么原因------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 晚上10:33
收件人: "TobiasLee/Chinese-Hip-pop-Generation"<Chinese-Hip-pop-Generation@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TobiasLee/Chinese-Hip-pop-Generation] 请问一你的CTEG那篇论文用的什么机器啊，感觉好慢啊 (#13)



1080Ti ，确实比较慢，需要一些耐心。
 
&mdash;

**Comment by chinayuyabin** [comment]
请问下您的那个CTEG的GAN跑了20个epoch花了多长时间啊！复现太难了！！！求告知
