### ISSUE TITLE
请问下您的那个CTEG的GAN跑了20个epoch花了多长时间啊！复现太难了！！！求告知

### ISSUE THREAD

**Issue by nlpofwhat** [TobiasLee/Chinese_Hip-pop_Generation#15]

**Comment by TobiasLee** [comment]
因为 Monte-Carlo 的时间和 n 以及句子长度 l 都有关，当时 ZHIHU 数据集的 l 大约是 60，n=16，这个设置之下大约一个 epoch 需要一个星期，我们是每隔一定步数在 valid 上做验证的，最好的结果大约在 2-5个 epoch 之间。

**Comment by nlpofwhat** [comment]
万分感谢🙏🙏------------------ 原始邮件 ------------------
发件人: "Tobias Lee"<notifications@github.com>
发送时间: 2020年1月6日(星期一) 中午11:18
收件人: "TobiasLee/Chinese-Hip-pop-Generation"<Chinese-Hip-pop-Generation@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TobiasLee/Chinese-Hip-pop-Generation] 请问下您的那个CTEG的GAN跑了20个epoch花了多长时间啊！复现太难了！！！求告知 (#15)



因为 Monte-Carlo 的时间和 n 以及句子长度 l 都有关，当时 ZHIHU 数据集的 l 大约是 60，n=16，这个设置之下大约一个 epoch 需要一个星期，我们是每隔一定步数在 valid 上做验证的，最好的结果大约在 2-5个 epoch 之间。
 
&mdash;
