### ISSUE TITLE
translate.py: error: the following arguments are required: index_file and TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by zhenhao-huang** [TobiasLee/Chinese_Hip-pop_Generation#17]
您好，根据说明我训练完成之后运行translate.py文件，出现translate.py: error: the following arguments are required: index_file报错，我查阅了网上资料说是需要在index_file参数前加--，加完之后我再次运行再次报错TypeError: expected str, bytes or os.PathLike object, not NoneType，排查完后发现参数设定为Namespace(index_file=None, input_file=None, refer_file=None, reverse='False')，请问要如何正确输入参数，希望您可以解答，谢谢

**Comment by TobiasLee** [comment]
应该是这样：
> python3 translate.py  index_file_name  --input_file  input_file_name  --refer_file refer_file_name

index_file_name 前不用 `--`

**Comment by TobiasLee** [comment]
应该是这样：
> python3 translate.py  index_file_name  --input_file  input_file_name  --refer_file refer_file_name

index_file_name 前不用 --

**Comment by zhenhao-huang** [comment]
> 应该是这样：
> 
> > python3 translate.py  index_file_name  --input_file  input_file_name  --refer_file refer_file_name
> 
> index_file_name 前不用 `--`
显示No such file or directory: 'index_file_name'。我没有index_file_name 、input_file_name 、refer_file_name这三个文件

**Comment by TobiasLee** [comment]
请把这三个文件名换成实际对应的生成出来的文件名

**Comment by zhenhao-huang** [comment]
![2b9e513bf701cc751bcdceb19090bff](https://user-images.githubusercontent.com/51730030/97775918-68fb9400-1b9f-11eb-94bc-14649054b34c.png)
训练完成后，生成的文件就只有model和result下的文件，不知这里的三个文件名是否分别对应指seq_gan-29.index，seq_gan-29.meta，seq_gan-29.data-00000-of-00001

**Comment by zhenhao-huang** [comment]
原来是生成的id文件，但是index_file_name 、input_file_name 、refer_file_name这三个文件表示什么

**Comment by TobiasLee** [comment]
> 原来是生成的id文件，但是index_file_name 、input_file_name 、refer_file_name这三个文件表示什么

index_file_name 就是生成的歌词 word index 文件，而后面两个就是原本的输入文件和对应的真实下一句歌词。

**Comment by zhenhao-huang** [comment]
谢谢

**Comment by fuweifuvtoo** [comment]
请问如何正确跑通这个呢?
python translate.py index_file_name --input_file input_file_name --refer_file refer_file_name

**Comment by fuweifuvtoo** [comment]
知道translate.py的作用了，是将生成的文本翻译成中文

python translate.py ./result/test_ret_final.txt --input_file ./data/test_idx_x_r.txt --refer_file ./data/test_idx_y_r.txt --reverse True

**Comment by zhenhao-huang** [comment]
> 知道translate.py的作用了，是将生成的文本翻译成中文
> 
> python translate.py ./result/test_ret_final.txt --input_file ./data/test_idx_x_r.txt --refer_file ./data/test_idx_y_r.txt --reverse True

是的
