### ISSUE TITLE
对源数据做jieba分词

### ISSUE THREAD

**Issue by zhenhao-huang** [TobiasLee/Chinese_Hip-pop_Generation#19]
博主，您对源数据做jieba分词时，有使用HMM模型和自定义词典吗，个人感觉不使用HMM模型效果更佳

**Comment by zhenhao-huang** [comment]
博主，为什么你的x，y文件内的数据这么相似，对源数据编码后为什么要打乱顺序

**Comment by TobiasLee** [comment]
> 博主，您对源数据做jieba分词时，有使用HMM模型和自定义词典吗，个人感觉不使用HMM模型效果更佳

使用的是默认的分词，没有其他的配置

**Comment by TobiasLee** [comment]
> 博主，为什么你的x，y文件内的数据这么相似，对源数据编码后为什么要打乱顺序

数据相似是指？我们的 x 是歌词的上句，y 是歌词的下句；打乱顺序是可选的，不打乱也行，一般都会对训练数据做 shuffle。

**Comment by zhenhao-huang** [comment]
生成的word index不在词表中是什么情况

**Comment by zhenhao-huang** [comment]
训练判别器中生成负样本数据的输入是x的数据，生成样本数据generate_paragraph.py输入是y的数据，这两个生成样本的输入有什么区别吗？对于押韵分词，有什么建议吗

**Comment by TobiasLee** [comment]
> 生成的word index不在词表中是什么情况

是会有 OOV 的问题存在的，正常现象。
