### ISSUE TITLE
如何生成table.npy

### ISSUE THREAD

**Issue by zhenhao-huang** [TobiasLee/Chinese_Hip-pop_Generation#21]
根据rhyme.py的提示，我生成了上句与下句的押韵奖励，但是长度远没有你的table.npy长，请问你是重复了1000次吗

**Comment by fuweifuvtoo** [comment]
同学，最近我也在看这个代码，能加你微信交流一下吗？

**Comment by fuweifuvtoo** [comment]
我的微信是 FWF19961004

**Comment by zhenhao-huang** [comment]
> 同学，最近我也在看这个代码，能加你微信交流一下吗？

可以的

**Comment by zhangbaijin** [comment]
同学你好，我运行了generative_paragraph.py 也有这个generative_paragraph.txt 但是txt里面是数字啊，应该怎么转换为中文呢，运行translate.py嘛？里面的参数咋设置的

**Comment by zhenhao-huang** [comment]
@zhangbaijin ，好像是运行·translate.py·，我只记得我自己写了一个转换

    word2idx = np.load("./w2i.npy")
    word2idx = word2idx.item()
    id2word = {k: v for v, k in zip(word2idx.keys(), word2idx.values())}
    str = ''
    with open('./generated_paragraph.txt', 'r') as f:
        for i in f:
            id = [int(a) for a in i.split()]
            text = [id2word[a] for a in id if a != 0]
            str += ''.join(text) + '\n'
        print(str)

    with open('./generated_paragraph_text.txt', 'w', encoding='utf-8') as f:
        f.write(str)
