### ISSUE TITLE
效果和预期差很多

### ISSUE THREAD

**Issue by fuweifuvtoo** [TobiasLee/Chinese_Hip-pop_Generation#24]
作者您好，我跑完您的代码，训练了30epoch之后，发现效果比预期差很多，而且大多数生成的句子都很长
不像您在示例中展示的那样，请问是我有哪里做错了吗？
例子如下:

> input:  你说你没听过我的名字huh
> refer:  我也没有听过你的名字huh
> translate:  一了百了伏笔传遍失落医生走上爱波激动坏单纯悍匪随身包懦弱接力攀升生动题目哀乐同花顺

**Comment by TobiasLee** [comment]
建议选取前 5 轮中的模型进行测试，对抗训练时间长了会导致语言模型被破坏
