### ISSUE TITLE
About the 'processed_inputs' in Generator

### ISSUE THREAD

**Issue by y52wang** [TobiasLee/Chinese_Hip-pop_Generation#7]
According to your document '我们采用了一个简单的全连接层（Fully Connected Layer），将输入句子的 Word Embedding 经过一个线性变化之后作为生成器的 LSTM。'

```python
self.processed_inputs = tf.transpose(tf.nn.embedding_lookup(self.g_embeddings, self.inputs), perm=[1, 0, 2])
# Here the tf.transpose seems very strange.
...
flatten = tf.reshape(self.processed_inputs, [self.batch_size, -1])
# The tf.transpose may conflict with the tf.reshape here, it broken the input sentences.
densed = tf.nn.xw_plus_b(flatten, self.encoder_W, self.encoder_b)  # batch
```

From my view, I think the tf.transpose may should be removed.

**Comment by TobiasLee** [comment]
Yes, the transpose operation seems redundant and confusing, you can remove it if you want. Besides, it is better to use an RNN as an encoder to encode the information of the input.
